name: Build and push Docker images

on:
  push:
    tags: '@openfn/ws-worker@**'

jobs:
  build-and-push-worker-image:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Branch name
        id: branch_name
        run: |
          SOURCE_TAG=${GITHUB_REF#refs/tags/}
          echo Source Tag: $SOURCE_TAG
          DOCKER_VERSION_TAG=${SOURCE_TAG#@}
          echo Version Tag: $DOCKER_VERSION_TAG
          echo "DOCKER_VERSION_TAG=$DOCKER_VERSION_TAG" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          target: ws-worker
          tags: |
            openfn/ws-worker:latest
            ${{ env.DOCKER_VERSION_TAG }}
